version: "2"
services:
  app:
    build:
      args:
        user: colus
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app:Appworkers
    container_name: gazpom-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - Appworkers
  nginx:
    image: nginx:alpine
    container_name: gazpom-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./etc/nginx/:/etc/nginx/conf.d/
    networks:
      - Appworkers

networks:
  Appworkers:
    driver: bridge
